In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv("fish.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [6]:
data["Species"]=le.fit_transform(data['Species'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    int32  
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), int32(1)
memory usage: 8.2 KB


In [7]:
i = data.iloc [:,1:7]
d = data.iloc [:,0]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (i, d, test_size = .30,random_state=0)

# GaussianNB

In [9]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [10]:
model.predict(x_test)

array([0, 4, 4, 4, 0, 2, 0, 2, 0, 4, 2, 3, 0, 2, 4, 4, 4, 3, 4, 0, 2, 6,
       4, 3, 4, 0, 0, 6, 0, 5, 0, 4, 3, 2, 0, 4, 6, 0, 0, 4, 0, 2, 4, 0,
       5, 4, 4, 4])

In [11]:
model.score(x_test,y_test)

0.5

# MultinomialNB

In [12]:
from sklearn.naive_bayes import MultinomialNB

In [13]:
clf = MultinomialNB()
clf.fit(i,d)

MultinomialNB()

In [14]:
clf.predict(x_test)

array([2, 5, 4, 4, 2, 0, 0, 4, 0, 4, 4, 2, 0, 0, 4, 4, 4, 3, 4, 0, 4, 2,
       4, 3, 4, 2, 0, 2, 0, 5, 0, 4, 3, 4, 0, 2, 2, 0, 0, 4, 2, 4, 4, 0,
       5, 4, 4, 4])

In [15]:
clf.score(x_test,y_test)

0.4166666666666667

# BernoulliNB

In [16]:
from sklearn.naive_bayes import BernoulliNB

In [17]:
bnb= BernoulliNB()

In [18]:
bnb.fit(i,d)

BernoulliNB()

In [19]:
bnb.predict(x_test)

array([2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2])

In [20]:
bnb.score(x_test,y_test)

0.3958333333333333